from django.utils.translation import ugettext_lazy as _
EU_COUNTRY_LIST =   ['AT',
                    'BE',
                    'BA',
                    'BG',
                    'HR',
                    'CY',
                    'CZ',
                    'DK',
                    'EE',
                    'FI',
                    'FR',
                    'DE',
                    'EL',
                    'HU',
                    'IE',
                    'IT',
                    'LV',
                    'LT',
                    'LU',
                    'MT',
                    'NL',
                    'PL',
                    'PT',
                    'RO',
                    'RS',
                    'SK',
                    'SI',
                    'ES',
                    'SE']
EU_COUNTRY_LIST_SQL = '(\'AT\',\'BE\',\'BA\',\'BG\',\'HR\',\'CY\',\'CZ\',\'DK\',\'EE\',\'FI\',\'FR\',\'DE\',\'EL\',\'HU\',\'IE\',\'IT\',\'LV\',\'LT\',\'LU\',\'MT\',\'NL\',\'PL\',\'PT\',\'RO\',\'RS\',\'SK\',\'SI\',\'ES\',\'SE\')'
COUNTRIES = (
    ('', ''),
    ('EU', _('EU-28')),
    ('AT', _('Austria')),
    ('BE', _('Belgium')),
    ('BA', _('Bosnia and Herzegovina')),
    ('BG', _('Bulgaria')),
    ('HR', _('Croatia')),
    ('CY', _('Cyprus')),
    ('CZ', _('Czech Republic')),
    ('DK', _('Denmark')),
    ('EE', _('Estonia')),
    ('FI', _('Finland')),
    ('FR', _('France')),
    ('DE', _('Germany')),
    ('EL', _('Greece')),
    ('HU', _('Hungary')),
    ('IE', _('Ireland')),
    ('IT', _('Italy')),
    ('LV', _('Latvia')),
    ('LT', _('Lithuania')),
    ('LU', _('Luxembourg')),
    ('MT', _('Malta')),
    ('NL', _('Netherlands')),
    ('PL', _('Poland')),
    ('PT', _('Portugal')),
    ('RO', _('Romania')),
    ('RS', _('Serbia')),
    ('SK', _('Slovak Republic')),
    ('SI', _('Slovenia')),
    ('ES', _('Spain')),
    ('SE', _('Sweden')),
    ('CH', _('Switzerland')),
    ('TR', _('Turkey')),
    ('CA', _('Canada')),
    ('UK', _('United Kingdom')),
    ('US', _('United States')),
)

ORGANIZATIONSIZE = (
    ('',''),
    ('MICRO',_('Micro enterprises')),
    ('SMALL',_('Small enterprises')),
    ('MEDIUM',_('Medium-sized enterprises')),
    ('LARGE',_('Large enterprises')),
)

BUILDINGTYPE = (
   ('',''),
   ('DETACHED',_('Detached single family dwellings')),
   ('data centre',_('Data centre')),
   ('SINGLE',_('Other single family dwellings')),
   ('MULTI4',_('Multi-family buildings 1-4 storeys')),
   ('MULTI5',_('Multi-family buidings 5+ storeys')),
   ('PRIVATE',_('Office buildings')),
   ('PUBLIC',_('Public buildings')),
   ('WHOLESALE',_('Wholesale and retail sector')),
   ('HOTEL',_('Hotels & restaurants')),
   ('HEALTH',_('Health care')),
   ('EDUCATION',_('Educational buildings')),
   ('SPORT',_('Sport Facilities')),
   ('INDUSTRY',_('Industry')),
)

OWNERSHIP = (
   ('',''),
   ('OWN',_('owned')),
   ('RENT',_('rented')),
)

VERIFIED = (
  ('',''),
  ('By third party',_('By third party')),
  ('by ESCO',_('By ESCO')),
  ('by other',_('By other')),
  ('not verified',_('Not verified')),
)

VERIFIED_SIMPLE = (
  ('',''),
  ('Verified',_('Verified')),
  ('Non-verified',_('Non-verified')),
  ('Unknown',_('Unknown')),
)

MEASURETYPES = (
  ('',''),
  ('Building Fabric Measures', _('Building Fabric Measures')),
  ('Combination of Building Fabric and HVAC', _('Combination of Building Fabric and HVAC')),
  ('Compressed Air', _('Compressed Air')),
  ('Cooling', _('Cooling')),
  ('Heating', _('Heating')),
  ('HVAC Plant', _('HVAC Plant')),
  ('ICT', _('ICT')),
  ('Integrated Renovation', _('Integrated Renovation')),
  ('Lighting', _('Lighting')),
  ('Metering, Monitoring and Energy Management', _('Metering, Monitoring and Energy Management')),
  ('Motors', _('Motors')),
  ('Power Systems', _('Power Systems')),
  ('Pumps', _('Pumps')),
  ('Refrigeration', _('Refrigeration')),
  ('Street Lighting', _('Street Lighting')),
  ('Ventilation and air conditioning', _('Ventilation and air conditioning')),
  ('Waste heat (without power generation)', _('Waste heat (without power generation)')),
  ('Waste heat (with power generation)', _('Waste heat (with power generation)')),
  ('Other', _('Other')),
)

MEASURETYPES_INDUSTRY = (
  ('',''),
  ('Compressed Air', _('Compressed Air')),
  ('Cooling', _('Cooling')),
  ('Heating', _('Heating')),
  ('ICT', _('ICT')),
  ('Metering, Monitoring and Energy Management', _('Metering, Monitoring and Energy Management')),
  ('Motors', _('Motors')),
  ('Power Systems', _('Power Systems')),
  ('Pumps', _('Pumps')),
  ('Refrigeration', _('Refrigeration')),
  ('Street Lighting', _('Street Lighting')),
  ('Waste heat (without power generation)', _('Waste heat (without power generation)')),
  ('Waste heat (with power generation)', _('Waste heat (with power generation)')),
  ('Other', _('Other')),
)

MEASURETYPES_BUILDING = (
  ('',''),
  ('Building Fabric Measures', _('Building Fabric Measures')),
  ('Combination of Building Fabric and HVAC', _('Combination of Building Fabric and HVAC')),
  ('Integrated Renovation', _('Integrated Renovation')),
  ('Lighting', _('Lighting')),
  ('HVAC Plant', _('HVAC Plant')),
  ('Ventilation and air conditioning', _('Ventilation and air conditioning')),
  ('Other', _('Other')),
)

SHARINGLEVEL = (
  ('PRI',_('Private')),
  ('ANA',_('Shared for analysis')),
)

#Dropdownlist contain other
INVESTMENTBUILDING =(
  ('Building',_('Building')),
  ('Industry',_('Industry')),
  ('Lighting', _('Lighting')),
  ('District heating',_('District heating')),
  ('Other',_('Other')),
)

INDUSTRYSECTOR =(
  ('Accommodation and food service',_('Accommodation and food service')),
  ('Administrative and support services', _('Administrative and support services')),
  ('Agriculture/forestry/fishing', _('Agriculture/forestry/fishing')),
  ('Arts, entertainment and recreation', _('Arts, entertainment and recreation')),
  ('Construction', _('Construction')),
  ('Education', _('Education')),
  ('Electricity, gas, steam and air conditioning supply', _('Electricity, gas, steam and air conditioning supply')),
  ('Finance/insurance', _('Finance/insurance')),
  ('Human health and social work', _('Human health and social work')),
  ('Information and communication', _('Information and communication')),
  ('Manufacturing', _('Manufacturing')),
  ('Mining/quarrying', _('Mining/quarrying')),
  ('Professional, scientific and technical', _('Professional, scientific and technical')),
  ('Public administration and defence', _('Public administration and defence')),
  ('Real estate', _('Real estate')),
  ('Transportation and storage', _('Transportation and storage')),
  ('Water/waste management', _('Water/waste management')),
  ('Wholesale and retail trade/motor vehicles', _('Wholesale and retail trade/motor vehicles')),
  ('Other', _('other')),
)

SOURCECONSUMPTIONBEFORE = (
  ('Energy audit actual', _('Energy audit actual')),
  ('energy audit norm', _('energy audit norm')),
  ('feasibility study', _('feasibility study')),
  ('other', _('other')),
)

BASISFORECAST = (
  ('Energy audit actual', _('Energy audit actual')),
  ('energy audit norm', _('energy audit norm')),
  ('feasibility study', _('feasibility study')),
  ('other', _('other')),
)

SOURCECONSUMPTIONAFTER = (
  ('Ex post energy audit actual', _('Ex post energy audit actual')),
  ('ex post energy audit norm', _('ex post energy audit norm')),
  ('actual reported by building manager', _('actual reported by building manager')),
  ('other', _('other')),
)

SATISFACTION = (
  ('signficantly worse than expected', _('signficantly worse than expected')),
  ('slightly worse than expected', _('slightly worse than expected')),
  ('as expected', _('as expected')),
  ('slightly better than expected', _('slightly better than expected')),
  ('signficantly better than expected', _('signficantly better than expected')),
)

NATUREORGANIZATION = (
    ('Public bank', _('Public bank')),
    ('Private bank', _('Private bank')),
    ('IFI', _('IFI')),
    ('ESCO', _('ESCO')),
    ('Scheme manager', _('Scheme manager')),
    ('Supplier', _('Supplier')),
    ('Host Investor', _('Host Investor')),
    ('other', _('other')),
)

CLIMATEZONES = (
    ('Mediteranian mountain', _('Mediteranian')),
    ('Mediteranian coastal', _('Mediteranian coastal')),
    ('Baltic coastal', _('Baltic coastal')),
    ('Central flatlands', _('Central flatlands')),
)

MEASURESTOCOLOR = (
  ('',''),
  ('Heating', '#d11a1a'),
  ('Cooling', '#2599d3'),
  ('Ventilation and air conditioning', '#756760'),
  ('Lighting', '#ac9212'),
  ('Compressed Air', '#ff751a'),
  ('Waste heat (without power generation)', '#d22582'),
  ('Waste heat (with power generation)', '#3f24d4'),
  ('Power Systems', '#414141'),
  ('Refrigeration', '#3f24d4'),
  ('Motors', '#04757c'),
  ('Pumps', '#b8e122'),
  ('Building Fabric Measures', '#1ad11a'),
  ('Other', '#6f9175'),
  ('HVAC Plant', '#d3977d'),
  ('Integrated Renovation','#04757c'),
  ('ICT','#414141'),
  ('Combination of Building Fabric and HVAC','#d22582'),
  ('Metering, Monitoring and Energy Management','Metering, Monitoring and Energy Management'),
  ('Street Lighting','#d11a1a'),
)

BUILDINGTOCOLOR = (
   ('',''),
   ('DETACHED','#d11a1a'),
   ('SINGLE','#2599d3'),
   ('MULTI4','#d0d0d0'),
   ('MULTI5','#2599d3'),
   ('PRIVATE','#ff751a'),
   ('PUBLIC','#ac9212'),
   ('WHOLESALE','purple'),
   ('HOTEL','#3f24d4'),
   ('HEALTH','#d11a1a'),
   ('EDUCATION','#756760'),
   ('SPORT','#1ad11a'),
   ('INDUSTRY','#16a085'),
)

AGGREGATES = (
    ('', _('(No aggregate)')),
    ('AVG', _('Average')),
    ('SUM', _('Sum')),
    ('COUNT', _('Count')),
    ('MIN', _('Minimum')),
    ('MAX', _('Maximum')),
    ('PERCENTILE_CONT_10', _("Percentile 10% (continuous)")),
    ('PERCENTILE_CONT_25', _("Percentile 25% (continuous)")),
    ('PERCENTILE_CONT_50', _("Median")),
    ('PERCENTILE_CONT_75', _("Percentile 75% (continuous)")),
    ('PERCENTILE_CONT_90', _("Percentile 90% (continuous)")),
    ('STDDEV', _("Standard Deviation")),
)

SAMPLE_SIZE_LIMIT = (
    ('50', _('Highly significant (n=50)')),
    ('20', _('Significant (n=20)')),
    ('10', _('Uncertain (n=10)')),
)

CATEGORY_VARIABLES = (
    ('country_3', _('Country')),
    ('measures_main', _('Measure type')),
    ('havetheprojectenergysavingsbeenverified_42', _('Verification')),
    ('organizationsize_14', _('Organization size')),
    ('buildingtype_15', _('Building type')),
    ('indicator_climate_G', _('Climate')),
    ('industrysector_13', _('Industry Sector/Organisation type. ')),
    ('ownership_16', _('Building ownership')),
    ('istheinvestmentinabuilding_12', _('Industry or Building')),
    ('financialperformance_68', _('Actual financial performance compared with expectation')),
    ('overallsatisfaction_69', _('Overall satisfaction with the investment')),
    ('whatisthebasisoftheforecast_37', _('Basis of the forecast')),
    ('sourceofconsumptionafter_41', _('Data source of consumption AFTER intervention (\'actual\')')),
    ('sourceofconsumptionbefore_35', _('Data source of consumption BEFORE intervention (\'actual\')')),
    ('hastheadjustedenergysavingsverified_95', _('Adjusted project energy savings Verification')),
    ('nonfinancialbenefits_67', _('Additional benefits triggered by the project')),
    ('keyreasonsformakinginvestment_66', _('Key reasons for making investment')),
)

DATE_CATEGORY_VARIABLES = (
    ('projectstartdate_28', _('Project start date')),
    ('dateinvestmentbecameoperational_29', _('Date investment became operational')),
)

VALUE_VARIABLES = (
    ('valueofeeinvestment_51', _('Total investment')),
    ('floorarea_17', _('Floor area')),
    ('energyconsumptionbefore_31', _('Energy Consumption BEFORE intervention (actual)')),
    ('predictedenergyconsumptionafter_36', _('Energy FORECAST')),
    ('energyconsumptionafter_38', _('Energy Consumption AFTER intervention (actual)')),
    #  ('nmuber_of_', _('Total investment')),
    ('netannualsaving_55', _('Energy cost saving')),
    ('indicator_simple_payback_time_AA', _('Simple payback time')),
    ('indicator_grouped_simple_payback_time_AB', _('Simple payback time grouped')),
    ('indicator_other_saving_time_W', _('Other saving')),
    ('indicator_avoidance_cost0', _('Avoidance costs')),
    ('indicator_area_CAPEX_AU', _('Area CAPEX')),
    ('indicator_unit_energy_before_AC', _('Unit energy BEFORE')),
    ('indicator_unit_energy_forecast_AD', _('Unit energy FORECAST')),
    ('indicator_unit_energy_after_AE', _('Unit energy AFTER')),
    ('indicator_unit_energy_saved_actual_AI', _('Unit energy saved ACTUAL')),
    ('indicator_energy_saved_AK', _('Total energy saved ACTUAL')),
    ('indicator_saving_pct_forecast_AL', _('Saving pct FORECAST')),
    ('indicator_saving_pct_actual_AM', _('Saving pct ACTUAL')),
    ('indicator_forecast_optimism_AN', _('FORECAST optimism')),
    ('energydemandbefore_19', _('Energy demand before investment')),
    ('energydemandafter_20', _('Energy demand after investment')),
    ('initialcapacity_21', _('Total initial capacity (kW)')),
    ('uvaluebefore_22', _('U-value (W/m2K) before investment')),
    ('uvalueafter_23', _('U-value (W/m2K) after investment')),
    ('arearenovated_24', _('Area renovated (m2)')),
    ('efficiencybefore_25', _('Efficiency before investment (%)')),
    ('efficiencyafter_26', _('Efficiency after investment (%)')),
    ('sizeoftheHVACPlant_27', _('Size of HVAC Plant (kW)')),
    ('averagelifetimeofmeasures_30', _('Average lifetime of measures (approx) (years)')),
    ('energyperformancecertificateafter_39', _('Energy Performance Certificate rating AFTER intervention')),
    ('productionrate_44', _('Productivity (adjustment factor)')),
    ('floorarea_45', _('The floor area')),
    ('comfort_46', _('Comfort (adjustment factor)')),
    ('heatingload_47', _('Heating load (adjustment factor)')),
    ('coolingload_48', _('Cooling load (adjustment factor)')),
    ('totalvalueofasset_49', _('Total Value of Asset')),
    ('totalvalueofinvestment_50', _('Total Value of investment')),
    ('annualenergycostsavings_52', _('Annual energy cost savings')),
    ('additionalfinancialbenefits_53', _('Additional financial benefits')),
    ('additionalcosts_54', _('Additional costs')),
    #('netannualsaving_55', _('Net annual saving')),
    ('npvprior_56', _('NPV (computed prior to investment)')),
    ('npvactual_57', _('NPV actual')),
    ('irrprior_58', _('IRR (computed prior to investment)')),
    ('irractual_59', _('IRR actual')),
    ('valueofgrant_61', _('Value of grant/subsidy')),
    ('valueofloan_63', _('Value of loan (if any) (in Euro)')),
    ('loanrepaymentterm_64', _('Loan repayment term')),
    ('interestrate_65', _('Interest rate')),
    ('energysavingstotal_71', _('Energy savings, total')),
    ('energysavingsgridelectricity_72', _('Energy savings, grid electricity')),
    ('energysavingsgas_73', _('Energy savings, gas')),
    ('energysavingsoil_74', _('Energy savings, oil')),
    ('energysavingscoal_75', _('Energy savings, coal/coal-based products')),
    ('energysavingsdistrictheating_76', _('Energy savings, district heating')),
    ('energysavingsdistrictcooling_77', _('Energy savings, district cooling')),
    ('energysavingsCHP_78', _('Energy savings, CHP')),
    ('energysavingsbiomass_79', _('Energy savings, biomass')),
    ('energysavingsbiofuels_80', _('Energy savings, biofuels')),
    ('energysavingselectricity_81', _('Energy savings, renewable electricity')),
    ('energysavingsrenewableheat_82', _('Energy savings, renewable heat')),
    ('adjustedenergysavingstotal_83', _('Energy savings adjusted for weather/season/production, total')),
    ('adjustedenergysavingstotalgridelectricity_84', _('Energy savings adjusted for weather/season/production, grid electricity')),
    ('adjustedenergysavingstotalgas_85', _('Energy savings adjusted for weather/season/production, gas')),
    ('adjustedenergysavingstotaloil_86', _('Energy savings adjusted for weather/season/production, oil')),
    ('adjustedenergysavingstotalcoal_87', _('Energy savings adjusted for weather/season/production, coal/coal-based products')),
    ('adjustedenergysavingstotaldistrictheating_88', _('Energy savings adjusted for weather/season/production, district heating')),
    ('adjustedenergysavingstotaldistrictcooling_89', _('Energy savings adjusted for weather/season/production, district cooling')),
    ('adjustedenergysavingstotalCHP_90', _('Energy savings adjusted for weather/season/production, CHP')),
    ('adjustedenergysavingstotalbiomass_91', _('Energy savings adjusted for weather/season/production, biomass')),
    ('adjustedenergysavingstotalbiofuels_92', _('Energy savings adjusted for weather/season/production, biofuels')),
    ('adjustedenergysavingstotalrenewableelectricity_93', _('Energy savings adjusted for weather/season/production, renewable electricity')),
    ('adjustedenergysavingstotalrenewableheat_94', _('Energy savings adjusted for weather/season/production, renewable heat')),
    ('energypricebeforetotal_96', _('Energy price before intervention, EUR/kWh, total')),
    ('energypricebeforegridelectricity_97', _('Energy price before intervention, EUR/kWh, grid electricity')),
    ('energypricebeforegas_98', _('Energy price before intervention, EUR/kWh, gas')),
    ('energypricebeforeoil_99', _('Energy price before intervention, EUR/kWh, oil')),
    ('energypricebeforecoal_100', _('Energy price before intervention, EUR/kWh, coal/coal-based products')),
    ('energypricebeforedistrictheating_101', _('Energy price before intervention, EUR/kWh, district heating')),
    ('energypricebeforedistrictcooling_102', _('Energy price before intervention, EUR/kWh, district cooling')),
    ('energypricebeforeCHP_103', _('Energy price before intervention, EUR/kWh, CHP')),
    ('energypricebeforebiomass_104', _('Energy price before intervention, EUR/kWh, biomass')),
    ('energypricebeforebiofuels_105', _('Energy price before intervention, EUR/kWh, biofuels')),
    ('energypricebeforerenewableelectricity_106', _('Energy price before intervention, EUR/kWh, renewable electricity')),
    ('energypricebeforerenewableheat_107', _('Energy price before intervention, EUR/kWh, renewable heat')),
    ('energypriceaftertotal_108', _('Energy price after intervention, EUR/kWh, total')),
    ('energypriceaftergridelectricity_109', _('Energy price after intervention, EUR/kWh, grid electricity')),
    ('energypriceaftergas_110', _('Energy price after intervention, EUR/kWh, gas')),
    ('energypriceafteroil_111', _('Energy price after intervention, EUR/kWh, oil')),
    ('energypriceaftercoal_112', _('Energy price after intervention, EUR/kWh, coal/coal-based products')),
    ('energypriceafterdistrictheating_113', _('Energy price after intervention, EUR/kWh, district heating')),
    ('energypriceafterdistrictcooling_114', _('Energy price after intervention, EUR/kWh, district cooling')),
    ('energypriceafterCHP_115', _('Energy price after intervention, EUR/kWh, CHP')),
    ('energypriceafterbiomass_116', _('Energy price after intervention, EUR/kWh, biomass')),
    ('energypriceafterbiofuels_117', _('Energy price after intervention, EUR/kWh, biofuels')),
    ('energypriceafterrenewableelectricity_118', _('Energy price after intervention, EUR/kWh, renewable electricity')),
    ('energypriceafterrenewableheat_119', _('Energy price after intervention, EUR/kWh, renewable heat')),
    ('energyconsbeforegridelectricity_120', _('Energy consumption before intervention, grid electricity')),
    ('energyconsbeforegas_121', _('Energy consumption before intervention, gas')),
    ('energyconsbeforeoil_122', _('Energy consumption before intervention, oil')),
    ('energyconsbeforecoal_123', _('Energy consumption before intervention, coal/coal-based products')),
    ('energyconsbeforedistrictheating_124', _('Energy consumption before intervention, district heating')),
    ('energyconsbeforedistrictcooling_125', _('Energy consumption before intervention, district cooling')),
    ('energyconsbeforeCHP_126', _('Energy consumption before intervention, CHP')),
    ('energyconsbeforebiomass_127', _('Energy consumption before intervention, biomass')),
    ('energyconsbeforebiofuels_128', _('Energy consumption before intervention, biofuels')),
    ('energyconsbeforerenewableelectricity_129', _('Energy consumption before intervention, renewable electricity')),
    ('energyconsbeforerenewableheat_130', _('Energy consumption before intervention, renewable heat')),
    ('energyconsbeforespaceheating_131', _('Energy consumption before intervention, space heating')),
    ('energyconsbeforespacecooling_132', _('Energy consumption before intervention, space cooling')),
    ('energyconsbeforewaterheating_133', _('Energy consumption before intervention, water heating')),
    ('energyconsbeforeventilation_134', _('Energy consumption before intervention, ventilation')),
    ('energyconsbeforerefrigeration_135', _('Energy consumption before intervention, refrigeration')),
    ('energyconsbeforepumps_136', _('Energy consumption before intervention, pumps and fans')),
    ('energyconsbeforecatering_137', _('Energy consumption before intervention, catering')),
    ('energyconsbeforeprocessenergy_138', _('Energy consumption before intervention, process energy')),
    ('energyconsbeforelighting_139', _('Energy consumption before intervention, lighting')),
    ('energyconsbeforeappliances_140', _('Energy consumption before intervention, appliances')),
    ('energyconsaftergridelectricity_141', _('Energy consumption after intervention, grid electricity')),
    ('energyconsaftergas_142', _('Energy consumption after intervention, gas')),
    ('energyconsafteroil_143', _('Energy consumption after intervention, oil')),
    ('energyconsaftercoal_144', _('Energy consumption after intervention, coal/coal-based products')),
    ('energyconsafterdistrictheating_145', _('Energy consumption after intervention, district heating')),
    ('energyconsafterdistrictcooling_146', _('Energy consumption after intervention, district cooling')),
    ('energyconsafterCHP_147', _('Energy consumption after intervention, CHP')),
    ('energyconsafterbiomass_148', _('Energy consumption after intervention, biomass')),
    ('energyconsafterbiofuels_149', _('Energy consumption after intervention, biofuels')),
    ('energyconsafterrenewableelectricity_150', _('Energy consumption after intervention, renewable electricity')),
    ('energyconsafterrenewableheat_151', _('Energy consumption after intervention, renewable heat')),
    ('energyconsafterspaceheating_152', _('Energy consumption after intervention, space heating')),
    ('energyconsafterspacecooling_153', _('Energy consumption after intervention, space cooling')),
    ('energyconsafterwaterheating_154', _('Energy consumption after intervention, water heating')),
    ('energyconsafterventilation_155', _('Energy consumption after intervention, ventilation')),
    ('energyconsafterrefrigeration_156', _('Energy consumption after intervention, refrigeration')),
    ('energyconsafterpumps_157', _('Energy consumption after intervention, pumps and fans')),
    ('energyconsaftercatering_158', _('Energy consumption after intervention, catering')),
    ('energyconsafterprocessenergy_159', _('Energy consumption after intervention, process energy')),
    ('energyconsafterlighting_160', _('Energy consumption after intervention, lighting')),
    ('energyconsafterppliances_161', _('Energy consumption after intervention, appliances')),
    ('adjustedenergyconsbeforetotal_162', _('Energy consumption before intervention, adjusted for weather/season/production, total')),
    ('adjustedenergyconsbeforegridelectricity_163', _('Energy consumption before intervention, adjusted for weather/season/production, grid electricity')),
    ('adjustedenergyconsbeforegas_164', _('Energy consumption before intervention, adjusted for weather/season/production, gas')),
    ('adjustedenergyconsbeforeoil_165', _('Energy consumption before intervention, adjusted for weather/season/production, oil')),
    ('adjustedenergyconsbeforecoal_166', _('Energy consumption before intervention, adjusted for weather/season/production, coal/coal-based products')),
    ('adjustedenergyconsbeforedistrictheating_167', _('Energy consumption before intervention, adjusted for weather/season/production, district heating')),
    ('adjustedenergyconsbeforedistrictcooling_168', _('Energy consumption before intervention, adjusted for weather/season/production, district cooling')),
    ('adjustedenergyconsbeforeCHP_169', _('Energy consumption before intervention, adjusted for weather/season/production, CHP')),
    ('adjustedenergyconsbeforebiomass_170', _('Energy consumption before intervention, adjusted for weather/season/production, biomass')),
    ('adjustedenergyconsbeforebiofuels_171', _('Energy consumption before intervention, adjusted for weather/season/production, biofuels')),
    ('adjustedenergyconsbeforerenewableelectricity_172', _('Energy consumption before intervention, adjusted for weather/season/production, renewable electricity')),
    ('adjustedenergyconsbeforerenewableheat_173', _('Energy consumption before intervention, adjusted for weather/season/production, renewable heat')),
    ('adjustedenergyconsbeforespaceheating_174', _('Energy consumption before intervention, adjusted for weather/season/production, space heating')),
    ('adjustedenergyconsbeforespacecooling_175', _('Energy consumption before intervention, adjusted for weather/season/production, space cooling')),
    ('adjustedenergyconsbeforewaterheating_176', _('Energy consumption before intervention, adjusted for weather/season/production, water heating')),
    ('adjustedenergyconsbeforeventilation_177', _('Energy consumption before intervention, adjusted for weather/season/production, ventilation')),
    ('adjustedenergyconsbeforerefrigeration_178', _('Energy consumption before intervention, adjusted for weather/season/production, refrigeration')),
    ('adjustedenergyconsbeforepumps_179', _('Energy consumption before intervention, adjusted for weather/season/production, pumps and fans')),
    ('adjustedenergyconsbeforecatering_180', _('Energy consumption before intervention, adjusted for weather/season/production, catering')),
    ('adjustedenergyconsbeforeprocessenergy_181', _('Energy consumption before intervention, adjusted for weather/season/production, process energy')),
    ('adjustedenergyconsbeforelighting_182', _('Energy consumption before intervention, adjusted for weather/season/production, lighting')),
    ('adjustedenergyconsbeforeappliances_183', _('Energy consumption before intervention, adjusted for weather/season/production, appliances')),
    ('adjustedenergyconsaftertotal_184', _('Energy consumption after intervention, adjusted for weather/season/production, total')),
    ('adjustedenergyconsaftergridelectricity_185', _('Energy consumption after intervention, adjusted for weather/season/production, grid electricity')),
    ('adjustedenergyconsaftergas_186', _('Energy consumption after intervention, adjusted for weather/season/production, gas')),
    ('adjustedenergyconsafteroil_187', _('Energy consumption after intervention, adjusted for weather/season/production, oil')),
    ('adjustedenergyconsaftercoal_188', _('Energy consumption after intervention, adjusted for weather/season/production, coal/coal-based products')),
    ('adjustedenergyconsafterdistrictheating_189', _('Energy consumption after intervention, adjusted for weather/season/production, district heating')),
    ('adjustedenergyconsafterdistrictcooling_190', _('Energy consumption after intervention, adjusted for weather/season/production, district cooling')),
    ('adjustedenergyconsafterCHP_191', _('Energy consumption after intervention, adjusted for weather/season/production, CHP')),
    ('adjustedenergyconsafterbiomass_192', _('Energy consumption after intervention, adjusted for weather/season/production, biomass')),
    ('adjustedenergyconsafterbiofuels_193', _('Energy consumption after intervention, adjusted for weather/season/production, biofuels')),
    ('adjustedenergyconsafterrenewableelectricity_194', _('Energy consumption after intervention, adjusted for weather/season/production, renewable electricity')),
    ('adjustedenergyconsafterrenewableheat_195', _('Energy consumption after intervention, adjusted for weather/season/production, renewable heat')),
    ('adjustedenergyconsafterspaceheating_196', _('Energy consumption after intervention, adjusted for weather/season/production, space heating')),
    ('adjustedenergyconsafterspacecooling_197', _('Energy consumption after intervention, adjusted for weather/season/production, space cooling')),
    ('adjustedenergyconsafterwaterheating_198', _('Energy consumption after intervention, adjusted for weather/season/production, water heating')),
    ('adjustedenergyconsafterventilation_199', _('Energy consumption after intervention, adjusted for weather/season/production, ventilation')),
    ('adjustedenergyconsafterrefrigeration_200', _('Energy consumption after intervention, adjusted for weather/season/production, refrigeration')),
    ('adjustedenergyconsafterpumps_201', _('Energy consumption after intervention, adjusted for weather/season/production, pumps and fans')),
    ('adjustedenergyconsaftercatering_202', _('Energy consumption after intervention, adjusted for weather/season/production, catering')),
    ('adjustedenergyconsafterprocessenergy_203', _('Energy consumption after intervention, adjusted for weather/season/production, process energy')),
    ('adjustedenergyconsafterlighting_204', _('Energy consumption after intervention, adjusted for weather/season/production, lighting')),
    ('adjustedenergyconsafterappliances_205', _('Energy consumption after intervention, adjusted for weather/season/production, appliances')),
)

VALUE_VARIABLE_NAMES_LIST = [v[0] for v in VALUE_VARIABLES]

FILTER_VARIABLES = (
    ('country_3', _('Country')),
    ('measures_18__root_title', _('Investment type')),
    ('havetheprojectenergysavingsbeenverified_42', _('Verification')),
    ('organizationsize_14', _('Organization size')),
    ('buildingtype_15', _('Building type')),
    ('indicator_climate_G', _('Climate')),
    ('industrysector_13', _('Industry Sector/Organisation type. ')),
    ('ownership_16', _('Building ownership')),
    ('istheinvestmentinabuilding_12', _('Industry or Building')),
    ('financialperformance_68', _('Actual financial performance compared with expectation')),
    ('overallsatisfaction_69', _('Overall satisfaction with the investment')),
    ('whatisthebasisoftheforecast_37', _('Basis of the forecast')),
    ('sourceofconsumptionafter_41', _('Data source of consumption AFTER intervention (actual)')),
    ('sourceofconsumptionbefore_35', _('Data source of consumption BEFORE intervention (actual)')),
    ('hastheadjustedenergysavingsverified_95', _('Adjusted project energy savings Verification')),
    ('nonfinancialbenefits_67', _('Additional benefits triggered by the project')),
    ('keyreasonsformakinginvestment_66', _('Key reasons for making investment')),
    ('energyperformancecertificatebefore_32', _('Energy performance cerificate rating before intervention')),
    # ('projectstartdate_28', _('The project start date for energy efficiency investment (month /year)')),
    ('dateinvestmentbecameoperational_29', _('The Date investment became operational (month/year)')),
    ('methodologyforindependentverification_43', _('The methodology for independent verification (e.g. IPMVP)')),
    ('sourceoffinance_60', _('Source of finance')),
    ('provider_62', _('Provider')),
    ('floorarea_17', _('Floor area')),
    ('energyconsumptionbefore_31', _('Energy Consumption BEFORE intervention (actual)')),
    ('predictedenergyconsumptionafter_36', _('Energy FORECAST')),
    ('energyconsumptionafter_38', _('Energy Consumption AFTER intervention (actual)')),
    ('valueofeeinvestment_51', _('Total investment')),
    ('netannualsaving_55', _('Energy cost saving')),
    ('indicator_simple_payback_time_AA', _('Simple payback time')),
    ('indicator_grouped_simple_payback_time_AB', _('Simple payback time grouped')),
    ('indicator_other_saving_time_W', _('Other saving')),
    ('indicator_avoidance_cost0', _('Avoidance costs')),
    ('indicator_area_CAPEX_AU', _('Area CAPEX')),
    ('indicator_unit_energy_before_AC', _('Unit energy BEFORE')),
    ('indicator_unit_energy_forecast_AD', _('Unit energy FORECAST')),
    ('indicator_unit_energy_after_AE', _('Unit energy AFTER')),
    ('indicator_unit_energy_saved_actual_AI', _('Unit energy saved ACTUAL')),
    ('indicator_energy_saved_AK', _('Total energy saved ACTUAL')),
    ('indicator_saving_pct_forecast_AL', _('Saving pct FORECAST')),
    ('indicator_saving_pct_actual_AM', _('Saving pct ACTUAL')),
    ('indicator_forecast_optimism_AN', _('FORECAST optimism')),
    ('energydemandbefore_19', _('Energy demand before investment')),
    ('energydemandafter_20', _('Energy demand after investment')),
    ('initialcapacity_21', _('Total initial capacity (kW)')),
    ('uvaluebefore_22', _('U-value (W/m2K) before investment')),
    ('uvalueafter_23', _('U-value (W/m2K) after investment')),
    ('arearenovated_24', _('Area renovated (m2)')),
    ('efficiencybefore_25', _('Efficiency before investment (%)')),
    ('efficiencyafter_26', _('Efficiency after investment (%)')),
    ('sizeoftheHVACPlant_27', _('Size of HVAC Plant (kW)')),
    ('averagelifetimeofmeasures_30', _('Average lifetime of measures (approx) (years)')),
    ('energyperformancecertificateafter_39', _('Energy Performance Certificate rating AFTER intervention')),
    ('productionrate_44', _('Productivity (adjustment factor)')),
    ('floorarea_45', _('The floor area')),
    ('comfort_46', _('Comfort (adjustment factor)')),
    ('heatingload_47', _('Heating load (adjustment factor)')),
    ('coolingload_48', _('Cooling load (adjustment factor)')),
    ('totalvalueofasset_49', _('Total Value of Asset')),
    ('totalvalueofinvestment_50', _('Total Value of investment')),
    ('annualenergycostsavings_52', _('Annual energy cost savings')),
    ('additionalfinancialbenefits_53', _('Additional financial benefits')),
    ('additionalcosts_54', _('Additional costs')),
    #('netannualsaving_55', _('Net annual saving')),
    ('npvprior_56', _('NPV (computed prior to investment)')),
    ('npvactual_57', _('NPV actual')),
    ('irrprior_58', _('IRR (computed prior to investment)')),
    ('irractual_59', _('IRR actual')),
    ('valueofgrant_61', _('Value of grant/subsidy')),
    ('valueofloan_63', _('Value of loan (if any) (in Euro)')),
    ('loanrepaymentterm_64', _('Loan repayment term')),
    ('interestrate_65', _('Interest rate')),
    ('energysavingstotal_71', _('Energy savings, total')),
    ('energysavingsgridelectricity_72', _('Energy savings, grid electricity')),
    ('energysavingsgas_73', _('Energy savings, gas')),
    ('energysavingsoil_74', _('Energy savings, oil')),
    ('energysavingscoal_75', _('Energy savings, coal/coal-based products')),
    ('energysavingsdistrictheating_76', _('Energy savings, district heating')),
    ('energysavingsdistrictcooling_77', _('Energy savings, district cooling')),
    ('energysavingsCHP_78', _('Energy savings, CHP')),
    ('energysavingsbiomass_79', _('Energy savings, biomass')),
    ('energysavingsbiofuels_80', _('Energy savings, biofuels')),
    ('energysavingselectricity_81', _('Energy savings, renewable electricity')),
    ('energysavingsrenewableheat_82', _('Energy savings, renewable heat')),
    ('adjustedenergysavingstotal_83', _('Energy savings adjusted for weather/season/production, total')),
    ('adjustedenergysavingstotalgridelectricity_84', _('Energy savings adjusted for weather/season/production, grid electricity')),
    ('adjustedenergysavingstotalgas_85', _('Energy savings adjusted for weather/season/production, gas')),
    ('adjustedenergysavingstotaloil_86', _('Energy savings adjusted for weather/season/production, oil')),
    ('adjustedenergysavingstotalcoal_87', _('Energy savings adjusted for weather/season/production, coal/coal-based products')),
    ('adjustedenergysavingstotaldistrictheating_88', _('Energy savings adjusted for weather/season/production, district heating')),
    ('adjustedenergysavingstotaldistrictcooling_89', _('Energy savings adjusted for weather/season/production, district cooling')),
    ('adjustedenergysavingstotalCHP_90', _('Energy savings adjusted for weather/season/production, CHP')),
    ('adjustedenergysavingstotalbiomass_91', _('Energy savings adjusted for weather/season/production, biomass')),
    ('adjustedenergysavingstotalbiofuels_92', _('Energy savings adjusted for weather/season/production, biofuels')),
    ('adjustedenergysavingstotalrenewableelectricity_93', _('Energy savings adjusted for weather/season/production, renewable electricity')),
    ('adjustedenergysavingstotalrenewableheat_94', _('Energy savings adjusted for weather/season/production, renewable heat')),
    ('energypricebeforetotal_96', _('Energy price before intervention, EUR/kWh, total')),
    ('energypricebeforegridelectricity_97', _('Energy price before intervention, EUR/kWh, grid electricity')),
    ('energypricebeforegas_98', _('Energy price before intervention, EUR/kWh, gas')),
    ('energypricebeforeoil_99', _('Energy price before intervention, EUR/kWh, oil')),
    ('energypricebeforecoal_100', _('Energy price before intervention, EUR/kWh, coal/coal-based products')),
    ('energypricebeforedistrictheating_101', _('Energy price before intervention, EUR/kWh, district heating')),
    ('energypricebeforedistrictcooling_102', _('Energy price before intervention, EUR/kWh, district cooling')),
    ('energypricebeforeCHP_103', _('Energy price before intervention, EUR/kWh, CHP')),
    ('energypricebeforebiomass_104', _('Energy price before intervention, EUR/kWh, biomass')),
    ('energypricebeforebiofuels_105', _('Energy price before intervention, EUR/kWh, biofuels')),
    ('energypricebeforerenewableelectricity_106', _('Energy price before intervention, EUR/kWh, renewable electricity')),
    ('energypricebeforerenewableheat_107', _('Energy price before intervention, EUR/kWh, renewable heat')),
    ('energypriceaftertotal_108', _('Energy price after intervention, EUR/kWh, total')),
    ('energypriceaftergridelectricity_109', _('Energy price after intervention, EUR/kWh, grid electricity')),
    ('energypriceaftergas_110', _('Energy price after intervention, EUR/kWh, gas')),
    ('energypriceafteroil_111', _('Energy price after intervention, EUR/kWh, oil')),
    ('energypriceaftercoal_112', _('Energy price after intervention, EUR/kWh, coal/coal-based products')),
    ('energypriceafterdistrictheating_113', _('Energy price after intervention, EUR/kWh, district heating')),
    ('energypriceafterdistrictcooling_114', _('Energy price after intervention, EUR/kWh, district cooling')),
    ('energypriceafterCHP_115', _('Energy price after intervention, EUR/kWh, CHP')),
    ('energypriceafterbiomass_116', _('Energy price after intervention, EUR/kWh, biomass')),
    ('energypriceafterbiofuels_117', _('Energy price after intervention, EUR/kWh, biofuels')),
    ('energypriceafterrenewableelectricity_118', _('Energy price after intervention, EUR/kWh, renewable electricity')),
    ('energypriceafterrenewableheat_119', _('Energy price after intervention, EUR/kWh, renewable heat')),
    ('energyconsbeforegridelectricity_120', _('Energy consumption before intervention, grid electricity')),
    ('energyconsbeforegas_121', _('Energy consumption before intervention, gas')),
    ('energyconsbeforeoil_122', _('Energy consumption before intervention, oil')),
    ('energyconsbeforecoal_123', _('Energy consumption before intervention, coal/coal-based products')),
    ('energyconsbeforedistrictheating_124', _('Energy consumption before intervention, district heating')),
    ('energyconsbeforedistrictcooling_125', _('Energy consumption before intervention, district cooling')),
    ('energyconsbeforeCHP_126', _('Energy consumption before intervention, CHP')),
    ('energyconsbeforebiomass_127', _('Energy consumption before intervention, biomass')),
    ('energyconsbeforebiofuels_128', _('Energy consumption before intervention, biofuels')),
    ('energyconsbeforerenewableelectricity_129', _('Energy consumption before intervention, renewable electricity')),
    ('energyconsbeforerenewableheat_130', _('Energy consumption before intervention, renewable heat')),
    ('energyconsbeforespaceheating_131', _('Energy consumption before intervention, space heating')),
    ('energyconsbeforespacecooling_132', _('Energy consumption before intervention, space cooling')),
    ('energyconsbeforewaterheating_133', _('Energy consumption before intervention, water heating')),
    ('energyconsbeforeventilation_134', _('Energy consumption before intervention, ventilation')),
    ('energyconsbeforerefrigeration_135', _('Energy consumption before intervention, refrigeration')),
    ('energyconsbeforepumps_136', _('Energy consumption before intervention, pumps and fans')),
    ('energyconsbeforecatering_137', _('Energy consumption before intervention, catering')),
    ('energyconsbeforeprocessenergy_138', _('Energy consumption before intervention, process energy')),
    ('energyconsbeforelighting_139', _('Energy consumption before intervention, lighting')),
    ('energyconsbeforeappliances_140', _('Energy consumption before intervention, appliances')),
    ('energyconsaftergridelectricity_141', _('Energy consumption after intervention, grid electricity')),
    ('energyconsaftergas_142', _('Energy consumption after intervention, gas')),
    ('energyconsafteroil_143', _('Energy consumption after intervention, oil')),
    ('energyconsaftercoal_144', _('Energy consumption after intervention, coal/coal-based products')),
    ('energyconsafterdistrictheating_145', _('Energy consumption after intervention, district heating')),
    ('energyconsafterdistrictcooling_146', _('Energy consumption after intervention, district cooling')),
    ('energyconsafterCHP_147', _('Energy consumption after intervention, CHP')),
    ('energyconsafterbiomass_148', _('Energy consumption after intervention, biomass')),
    ('energyconsafterbiofuels_149', _('Energy consumption after intervention, biofuels')),
    ('energyconsafterrenewableelectricity_150', _('Energy consumption after intervention, renewable electricity')),
    ('energyconsafterrenewableheat_151', _('Energy consumption after intervention, renewable heat')),
    ('energyconsafterspaceheating_152', _('Energy consumption after intervention, space heating')),
    ('energyconsafterspacecooling_153', _('Energy consumption after intervention, space cooling')),
    ('energyconsafterwaterheating_154', _('Energy consumption after intervention, water heating')),
    ('energyconsafterventilation_155', _('Energy consumption after intervention, ventilation')),
    ('energyconsafterrefrigeration_156', _('Energy consumption after intervention, refrigeration')),
    ('energyconsafterpumps_157', _('Energy consumption after intervention, pumps and fans')),
    ('energyconsaftercatering_158', _('Energy consumption after intervention, catering')),
    ('energyconsafterprocessenergy_159', _('Energy consumption after intervention, process energy')),
    ('energyconsafterlighting_160', _('Energy consumption after intervention, lighting')),
    ('energyconsafterppliances_161', _('Energy consumption after intervention, appliances')),
    ('adjustedenergyconsbeforetotal_162', _('Energy consumption before intervention, adjusted for weather/season/production, total')),
    ('adjustedenergyconsbeforegridelectricity_163', _('Energy consumption before intervention, adjusted for weather/season/production, grid electricity')),
    ('adjustedenergyconsbeforegas_164', _('Energy consumption before intervention, adjusted for weather/season/production, gas')),
    ('adjustedenergyconsbeforeoil_165', _('Energy consumption before intervention, adjusted for weather/season/production, oil')),
    ('adjustedenergyconsbeforecoal_166', _('Energy consumption before intervention, adjusted for weather/season/production, coal/coal-based products')),
    ('adjustedenergyconsbeforedistrictheating_167', _('Energy consumption before intervention, adjusted for weather/season/production, district heating')),
    ('adjustedenergyconsbeforedistrictcooling_168', _('Energy consumption before intervention, adjusted for weather/season/production, district cooling')),
    ('adjustedenergyconsbeforeCHP_169', _('Energy consumption before intervention, adjusted for weather/season/production, CHP')),
    ('adjustedenergyconsbeforebiomass_170', _('Energy consumption before intervention, adjusted for weather/season/production, biomass')),
    ('adjustedenergyconsbeforebiofuels_171', _('Energy consumption before intervention, adjusted for weather/season/production, biofuels')),
    ('adjustedenergyconsbeforerenewableelectricity_172', _('Energy consumption before intervention, adjusted for weather/season/production, renewable electricity')),
    ('adjustedenergyconsbeforerenewableheat_173', _('Energy consumption before intervention, adjusted for weather/season/production, renewable heat')),
    ('adjustedenergyconsbeforespaceheating_174', _('Energy consumption before intervention, adjusted for weather/season/production, space heating')),
    ('adjustedenergyconsbeforespacecooling_175', _('Energy consumption before intervention, adjusted for weather/season/production, space cooling')),
    ('adjustedenergyconsbeforewaterheating_176', _('Energy consumption before intervention, adjusted for weather/season/production, water heating')),
    ('adjustedenergyconsbeforeventilation_177', _('Energy consumption before intervention, adjusted for weather/season/production, ventilation')),
    ('adjustedenergyconsbeforerefrigeration_178', _('Energy consumption before intervention, adjusted for weather/season/production, refrigeration')),
    ('adjustedenergyconsbeforepumps_179', _('Energy consumption before intervention, adjusted for weather/season/production, pumps and fans')),
    ('adjustedenergyconsbeforecatering_180', _('Energy consumption before intervention, adjusted for weather/season/production, catering')),
    ('adjustedenergyconsbeforeprocessenergy_181', _('Energy consumption before intervention, adjusted for weather/season/production, process energy')),
    ('adjustedenergyconsbeforelighting_182', _('Energy consumption before intervention, adjusted for weather/season/production, lighting')),
    ('adjustedenergyconsbeforeappliances_183', _('Energy consumption before intervention, adjusted for weather/season/production, appliances')),
    ('adjustedenergyconsaftertotal_184', _('Energy consumption after intervention, adjusted for weather/season/production, total')),
    ('adjustedenergyconsaftergridelectricity_185', _('Energy consumption after intervention, adjusted for weather/season/production, grid electricity')),
    ('adjustedenergyconsaftergas_186', _('Energy consumption after intervention, adjusted for weather/season/production, gas')),
    ('adjustedenergyconsafteroil_187', _('Energy consumption after intervention, adjusted for weather/season/production, oil')),
    ('adjustedenergyconsaftercoal_188', _('Energy consumption after intervention, adjusted for weather/season/production, coal/coal-based products')),
    ('adjustedenergyconsafterdistrictheating_189', _('Energy consumption after intervention, adjusted for weather/season/production, district heating')),
    ('adjustedenergyconsafterdistrictcooling_190', _('Energy consumption after intervention, adjusted for weather/season/production, district cooling')),
    ('adjustedenergyconsafterCHP_191', _('Energy consumption after intervention, adjusted for weather/season/production, CHP')),
    ('adjustedenergyconsafterbiomass_192', _('Energy consumption after intervention, adjusted for weather/season/production, biomass')),
    ('adjustedenergyconsafterbiofuels_193', _('Energy consumption after intervention, adjusted for weather/season/production, biofuels')),
    ('adjustedenergyconsafterrenewableelectricity_194', _('Energy consumption after intervention, adjusted for weather/season/production, renewable electricity')),
    ('adjustedenergyconsafterrenewableheat_195', _('Energy consumption after intervention, adjusted for weather/season/production, renewable heat')),
    ('adjustedenergyconsafterspaceheating_196', _('Energy consumption after intervention, adjusted for weather/season/production, space heating')),
    ('adjustedenergyconsafterspacecooling_197', _('Energy consumption after intervention, adjusted for weather/season/production, space cooling')),
    ('adjustedenergyconsafterwaterheating_198', _('Energy consumption after intervention, adjusted for weather/season/production, water heating')),
    ('adjustedenergyconsafterventilation_199', _('Energy consumption after intervention, adjusted for weather/season/production, ventilation')),
    ('adjustedenergyconsafterrefrigeration_200', _('Energy consumption after intervention, adjusted for weather/season/production, refrigeration')),
    ('adjustedenergyconsafterpumps_201', _('Energy consumption after intervention, adjusted for weather/season/production, pumps and fans')),
    ('adjustedenergyconsaftercatering_202', _('Energy consumption after intervention, adjusted for weather/season/production, catering')),
    ('adjustedenergyconsafterprocessenergy_203', _('Energy consumption after intervention, adjusted for weather/season/production, process energy')),
    ('adjustedenergyconsafterlighting_204', _('Energy consumption after intervention, adjusted for weather/season/production, lighting')),
    ('adjustedenergyconsafterappliances_205', _('Energy consumption after intervention, adjusted for weather/season/production, appliances')),
)

VARIABLE_UNITS = [
    ('floorarea_17', 'm²'),
    ('energyconsumptionbefore_31', 'MWh/a'),
    ('predictedenergyconsumptionafter_36', 'MWh/a'),
    ('energyconsumptionafter_38', 'MWh/a'),
    ('valueofeeinvestment_51', '€'),
    ('netannualsaving_55', '€'),
    ('indicator_simple_payback_time_AA', 'Years'),
    ('indicator_grouped_simple_payback_time_AB', 'Years'),
    ('indicator_other_saving_time_W', '%'),
    ('indicator_avoidance_cost_AT', '%'),
    ('indicator_avoidance_cost_lifetime','€/kWh'),
    ('indicator_area_CAPEX_AU', '€/m²'),
    ('indicator_unit_energy_before_AC', '€/kWh'),
    ('indicator_unit_energy_forecast_AD', '€/m²'),
    ('indicator_unit_energy_after_AE', '€/m²'),
    ('indicator_unit_energy_saved_actual_AI', '€/m²'),
    ('indicator_energy_saved_AK', 'kWh/a'),
    ('indicator_saving_pct_forecast_AL', '%'),
    ('indicator_saving_pct_actual_AM', '%'),
    ('indicator_forecast_optimism_AN', '%'),
    ('energydemandbefore_19', 'kWh/year'),
    ('energydemandafter_20', 'kWh/year'),
    ('initialcapacity_21', 'kW'),
    ('uvaluebefore_22', 'W/m2K'),
    ('uvalueafter_23', 'm²'),
    ('arearenovated_24', '%'),
    ('efficiencybefore_25', '%'),
    ('efficiencyafter_26', 'kW'),
    ('sizeoftheHVACPlant_27', 'Years'),
    ('averagelifetimeofmeasures_30', 'years'),
    ('energyperformancecertificateafter_39', ''),
    ('productionrate_44', '%'),
    ('floorarea_45', 'm²'),
    ('comfort_46', ''),
    ('heatingload_47', ''),
    ('coolingload_48', ''),
    ('totalvalueofasset_49', '€'),
    ('totalvalueofinvestment_50', '€'),
    ('annualenergycostsavings_52', '€/year'),
    ('additionalfinancialbenefits_53', '€/year'),
    ('additionalcosts_54', '€/year'),
    ('netannualsaving_55', '€'),
    ('npvprior_56', '€'),
    ('npvactual_57', '€'),
    ('irrprior_58', ''),
    ('irractual_59', ''),
    ('valueofgrant_61', '€'),
    ('valueofloan_63', '€'),
    ('loanrepaymentterm_64', '€'),
    ('interestrate_65', '%'),
    ('energysavingstotal_71', 'kWh/y'),
    ('energysavingsgridelectricity_72', 'kWh/y'),
    ('energysavingsgas_73', 'kWh/y'),
    ('energysavingsoil_74', 'kWh/y'),
    ('energysavingscoal_75', 'kWh/y'),
    ('energysavingsdistrictheating_76', 'kWh/y'),
    ('energysavingsdistrictcooling_77', 'kWh/y'),
    ('energysavingsCHP_78', 'kWh/y'),
    ('energysavingsbiomass_79', 'kWh/y'),
    ('energysavingsbiofuels_80', 'kWh/y'),
    ('energysavingselectricity_81', 'kWh/y'),
    ('energysavingsrenewableheat_82', 'kWh/y'),
    ('adjustedenergysavingstotal_83', 'kWh/y'),
    ('adjustedenergysavingstotalgridelectricity_84', 'kWh/y'),
    ('adjustedenergysavingstotalgas_85', 'kWh/y'),
    ('adjustedenergysavingstotaloil_86', 'kWh/y'),
    ('adjustedenergysavingstotalcoal_87', 'kWh/y'),
    ('adjustedenergysavingstotaldistrictheating_88', 'kWh/y'),
    ('adjustedenergysavingstotaldistrictcooling_89', 'kWh/y'),
    ('adjustedenergysavingstotalCHP_90', 'kWh/y'),
    ('adjustedenergysavingstotalbiomass_91', 'kWh/y'),
    ('adjustedenergysavingstotalbiofuels_92', 'kWh/y'),
    ('adjustedenergysavingstotalrenewableelectricity_93', 'kWh/y'),
    ('adjustedenergysavingstotalrenewableheat_94', 'kWh/y'),
    ('energypricebeforetotal_96', '€/kWh'),
    ('energypricebeforegridelectricity_97', '€/kWh'),
    ('energypricebeforegas_98', '€/kWh'),
    ('energypricebeforeoil_99', '€/kWh'),
    ('energypricebeforecoal_100', '€/kWh'),
    ('energypricebeforedistrictheating_101', '€/kWh'),
    ('energypricebeforedistrictcooling_102', '€/kWh'),
    ('energypricebeforeCHP_103', '€/kWh'),
    ('energypricebeforebiomass_104', '€/kWh'),
    ('energypricebeforebiofuels_105', '€/kWh'),
    ('energypricebeforerenewableelectricity_106', '€/kWh'),
    ('energypricebeforerenewableheat_107', '€/kWh'),
    ('energypriceaftertotal_108', '€/kWh'),
    ('energypriceaftergridelectricity_109', '€/kWh'),
    ('energypriceaftergas_110', '€/kWh'),
    ('energypriceafteroil_111', '€/kWh'),
    ('energypriceaftercoal_112', '€/kWh'),
    ('energypriceafterdistrictheating_113', '€/kWh'),
    ('energypriceafterdistrictcooling_114', '€/kWh'),
    ('energypriceafterCHP_115', '€/kWh'),
    ('energypriceafterbiomass_116', '€/kWh'),
    ('energypriceafterbiofuels_117', '€/kWh'),
    ('energypriceafterrenewableelectricity_118', '€/kWh'),
    ('energypriceafterrenewableheat_119', '€/kWh'),
    ('energyconsbeforegridelectricity_120', 'kWh/y'),
    ('energyconsbeforegas_121', 'kWh/y'),
    ('energyconsbeforeoil_122', 'kWh/y'),
    ('energyconsbeforecoal_123', 'kWh/y'),
    ('energyconsbeforedistrictheating_124', 'kWh/y'),
    ('energyconsbeforedistrictcooling_125', 'kWh/y'),
    ('energyconsbeforeCHP_126', 'kWh/y'),
    ('energyconsbeforebiomass_127', 'kWh/y'),
    ('energyconsbeforebiofuels_128', 'kWh/y'),
    ('energyconsbeforerenewableelectricity_129', 'kWh/y'),
    ('energyconsbeforerenewableheat_130', 'kWh/y'),
    ('energyconsbeforespaceheating_131', 'kWh/y'),
    ('energyconsbeforespacecooling_132', 'kWh/y'),
    ('energyconsbeforewaterheating_133', 'kWh/y'),
    ('energyconsbeforeventilation_134', 'kWh/y'),
    ('energyconsbeforerefrigeration_135', 'kWh/y'),
    ('energyconsbeforepumps_136', 'kWh/y'),
    ('energyconsbeforecatering_137', 'kWh/y'),
    ('energyconsbeforeprocessenergy_138', 'kWh/y'),
    ('energyconsbeforelighting_139', 'kWh/y'),
    ('energyconsbeforeappliances_140', 'kWh/y'),
    ('energyconsaftergridelectricity_141', 'kWh/y'),
    ('energyconsaftergas_142', 'kWh/y'),
    ('energyconsafteroil_143', 'kWh/y'),
    ('energyconsaftercoal_144', 'kWh/y'),
    ('energyconsafterdistrictheating_145', 'kWh/y'),
    ('energyconsafterdistrictcooling_146', 'kWh/y'),
    ('energyconsafterCHP_147', 'kWh/y'),
    ('energyconsafterbiomass_148', 'kWh/y'),
    ('energyconsafterbiofuels_149', 'kWh/y'),
    ('energyconsafterrenewableelectricity_150', 'kWh/y'),
    ('energyconsafterrenewableheat_151', 'kWh/y'),
    ('energyconsafterspaceheating_152', 'kWh/y'),
    ('energyconsafterspacecooling_153', 'kWh/y'),
    ('energyconsafterwaterheating_154', 'kWh/y'),
    ('energyconsafterventilation_155', 'kWh/y'),
    ('energyconsafterrefrigeration_156', 'kWh/y'),
    ('energyconsafterpumps_157', 'kWh/y'),
    ('energyconsaftercatering_158', 'kWh/y'),
    ('energyconsafterprocessenergy_159', 'kWh/y'),
    ('energyconsafterlighting_160', 'kWh/y'),
    ('energyconsafterppliances_161', 'kWh/y'),
    ('adjustedenergyconsbeforetotal_162', 'kWh/y'),
    ('adjustedenergyconsbeforegridelectricity_163', 'kWh/y'),
    ('adjustedenergyconsbeforegas_164', 'kWh/y'),
    ('adjustedenergyconsbeforeoil_165', 'kWh/y'),
    ('adjustedenergyconsbeforecoal_166', 'kWh/y'),
    ('adjustedenergyconsbeforedistrictheating_167', 'kWh/y'),
    ('adjustedenergyconsbeforedistrictcooling_168', 'kWh/y'),
    ('adjustedenergyconsbeforeCHP_169', 'kWh/y'),
    ('adjustedenergyconsbeforebiomass_170', 'kWh/y'),
    ('adjustedenergyconsbeforebiofuels_171', 'kWh/y'),
    ('adjustedenergyconsbeforerenewableelectricity_172', 'kWh/y'),
    ('adjustedenergyconsbeforerenewableheat_173', 'kWh/y'),
    ('adjustedenergyconsbeforespaceheating_174', 'kWh/y'),
    ('adjustedenergyconsbeforespacecooling_175', 'kWh/y'),
    ('adjustedenergyconsbeforewaterheating_176', 'kWh/y'),
    ('adjustedenergyconsbeforeventilation_177', 'kWh/y'),
    ('adjustedenergyconsbeforerefrigeration_178', 'kWh/y'),
    ('adjustedenergyconsbeforepumps_179', 'kWh/y'),
    ('adjustedenergyconsbeforecatering_180', 'kWh/y'),
    ('adjustedenergyconsbeforeprocessenergy_181', 'kWh/y'),
    ('adjustedenergyconsbeforelighting_182', 'kWh/y'),
    ('adjustedenergyconsbeforeappliances_183', 'kWh/y'),
    ('adjustedenergyconsaftertotal_184', 'kWh/y'),
    ('adjustedenergyconsaftergridelectricity_185', 'kWh/y'),
    ('adjustedenergyconsaftergas_186', 'kWh/y'),
    ('adjustedenergyconsafteroil_187', 'kWh/y'),
    ('adjustedenergyconsaftercoal_188', 'kWh/y'),
    ('adjustedenergyconsafterdistrictheating_189', 'kWh/y'),
    ('adjustedenergyconsafterdistrictcooling_190', 'kWh/y'),
    ('adjustedenergyconsafterCHP_191', 'kWh/y'),
    ('adjustedenergyconsafterbiomass_192', 'kWh/y'),
    ('adjustedenergyconsafterbiofuels_193', 'kWh/y'),
    ('adjustedenergyconsafterrenewableelectricity_194', 'kWh/y'),
    ('adjustedenergyconsafterrenewableheat_195', 'kWh/y'),
    ('adjustedenergyconsafterspaceheating_196', 'kWh/y'),
    ('adjustedenergyconsafterspacecooling_197', 'kWh/y'),
    ('adjustedenergyconsafterwaterheating_198', 'kWh/y'),
    ('adjustedenergyconsafterventilation_199', 'kWh/y'),
    ('adjustedenergyconsafterrefrigeration_200', 'kWh/y'),
    ('adjustedenergyconsafterpumps_201', 'kWh/y'),
    ('adjustedenergyconsaftercatering_202', 'kWh/y'),
    ('adjustedenergyconsafterprocessenergy_203', 'kWh/y'),
    ('adjustedenergyconsafterlighting_204', 'kWh/y'),
    ('adjustedenergyconsafterappliances_205', 'kWh/y'),
    ('indicator_avoidance_cost0', '€/kWh'),
]

BENCHMARKMETHOD = (
  ('indicator_avoidance_cost0', _('Avoidance costs (Eurocent/kWh)')),
  ('indicator_simple_payback_time_AA', _('Simple Payback Time (years)')),
  ('indicator_area_CAPEX_AU', _('Area cost (EUR/m2)')),
  ('indicator_saving_pct_other_AS', _('Others savings share (%)')),
  ('indicator_saving_pct_forecast_AL', _('Energy saved, forecast (%)')),
  ('indicator_saving_pct_actual_AM', _('Energy saved, realised (%)')),
)

DISCOUNT_RATE = (
    ('indicator_avoidance_cost0', '0%'),
    ('indicator_avoidance_cost1', '1%'),
    ('indicator_avoidance_cost2', '2%'),
    ('indicator_avoidance_cost3', '3%'),
    ('indicator_avoidance_cost4', '4%'),
    ('indicator_avoidance_cost5', '5%'),
    ('indicator_avoidance_cost6', '6%'),
    ('indicator_avoidance_cost7', '7%'),
    ('indicator_avoidance_cost8', '8%'),
    ('indicator_avoidance_cost9', '9%'),
    ('indicator_avoidance_cost10', '10%'),
    ('indicator_avoidance_cost11', '11%'),
    ('indicator_avoidance_cost12', '12%'),
    ('indicator_avoidance_cost13', '13%'),
    ('indicator_avoidance_cost14', '14%'),
    ('indicator_avoidance_cost15', '15%'),
)

BENCHMARKSECTOR =(
    ('Building', _('Building')),
  ('Industry', _('Industry')),
)
