from django.db import models
from django.contrib.auth.models import User
from derisk_app.lists import *

class Measure(models.Model):
  def __str__(self):
     return 'Measure: ' + self.title
  code = models.CharField(max_length=50, blank=False)
  title = models.CharField(max_length=200, blank=False)

class Benefit(models.Model):
  def __str__(self):
     return 'Benefit: ' + self.description
  description = models.CharField(max_length=50, blank=False)
 
# Create your models here.
class Project(models.Model):
    # General information
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User)
    sharing_level = models.CharField(help_text = 'Please describe the sharing level of this project',max_length=3,blank=False, default = 'PRI',choices = SHARINGLEVEL)
    title_2 = models.CharField(max_length=500, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    country_3 = models.CharField(help_text = 'The country of where the investment is located',max_length=4, blank=True, null=True, choices = COUNTRIES)              
    zipcode_4 = models.CharField(help_text = 'The Zip code of where the investment is located',max_length=500, blank=True, null=True)
    nutscode_4 = models.CharField(help_text = 'The NUTS code of where the investment is located',max_length=500, blank=True, null=True)
    city_5 = models.CharField(help_text = 'The city of where the investment is located',max_length=500, blank=True, null=True)
    fulladdress_6 = models.CharField(help_text = 'The full address of where the investment is located', max_length=500, blank=True, null=True)
    organizationname_7 = models.CharField(help_text = 'Host organization name', max_length=500, blank=True, null=True)
    sitename_8 = models.CharField(help_text = 'Host organization - Site name - location of investment',max_length=500, blank=True, null=True)
    contactperson_9 = models.CharField(help_text = 'The country of where the investment is located',max_length=500, blank=True, null=True)
    email_10 = models.EmailField(help_text = 'Host organization - Email',blank=True, null=True)
    telephone_11 = models.CharField(max_length=500, help_text='Host organization - Telephone',blank=True, null=True)
    istheinvestmentinabuilding_12 = models.CharField(max_length=500, help_text='Please select if  the investment is in a building, industry or infrastructure',blank=True, null=True, choices = INVESTMENTBUILDING)
    istheinvestmentinabuildingother_12 = models.CharField(max_length=500, help_text='Please specify other option',blank=True, null=True)
    industrysector_13 = models.CharField(max_length=500, help_text='Please select the Industry Sector/Organisation type.',blank=True, null=True, choices = INDUSTRYSECTOR)
    industrysectorother_13 = models.CharField(max_length=500, help_text='Please specify other for the Industry Sector/Organisation type. ',blank=True, null=True)
    organizationsize_14 = models.CharField(max_length=50, help_text='Please select the Organisation size. Leave blank for buildings.',blank=True, null=True, choices = ORGANIZATIONSIZE)
    buildingtype_15 = models.CharField(max_length=50, help_text='Please select the Building type',blank=True, null=True, choices = BUILDINGTYPE)
    ownership_16 = models.CharField(max_length=50, help_text='Please select the Ownership type',blank=True, null=True, choices = OWNERSHIP)
    floorarea_17 = models.DecimalField(max_digits=25, decimal_places=0,help_text='Please specify  the Floor area of building in m2 ',blank=True, null=True)
    measures_18 = models.ManyToManyField(Measure,help_text='Please select which measures are included in the investment. You can add more than one.',blank=True)
    energydemandbefore_19 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Only valid for measures 1 (Heating) to 10 (Pumps), Please  specify total annual energy demand for relevant components before investment (kWh/y). Relevant components means the components that are included in the project. ',blank=True, null=True)
    energydemandafter_20 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please  specify total annual energy demand for relevant components after investment (kWh/y). Relevant components means the components that are included in the project. Only valid for measures 1 (Heating) to 10 (Pumps)',blank=True, null=True)
    initialcapacity_21 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please  specify total initial capacity (kW) for relevant components. Relevant components means the components that are included in the project. If more components, use weighed average of relevant components. Only valid for measures 1 (Heating) to 10 (Pumps)',blank=True, null=True)
    uvaluebefore_22 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify U-value (W/m2K), for relevant building components before investment. If more individual components, enter weighed average value for relevant components. Only valid for measures 12 - Building Fabric Measures',blank=True, null=True)
    uvalueafter_23 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify U-value (W/m2K), for relevant building components after investment. If more individual components, enter weighed average value for relevant components. Only valid for measures 12 - Building Fabric Measures',blank=True, null=True)
    arearenovated_24 = models.DecimalField(max_digits=25, decimal_places=0,help_text='Please specify area renovated (m2). Only valid for measures 12 - Building Fabric Measures',blank=True, null=True)
    efficiencybefore_25 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify efficiency before investment (%). Only valid for measures 13 - HVAC Plant',blank=True, null=True)
    efficiencyafter_26 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify  efficiency after investment  (%).Only valid for measures 13 - HVAC Plant',blank=True, null=True)
    sizeoftheHVACPlant_27 = models.DecimalField(max_digits=25, decimal_places=4,max_length=500, help_text='Please specify  size (kW).Only valid for measures 13 - HVAC Plant',blank=True, null=True)
    projectstartdate_28 = models.CharField(max_length=10,help_text='Please state the project start date for energy efficiency investment (month /year)',blank=True, null=True)
    dateinvestmentbecameoperational_29 = models.CharField(max_length=10,help_text='Please state the Date investment became operational (month/year)',blank=True, null=True)
    averagelifetimeofmeasures_30 = models.IntegerField(help_text='Please state the  Average lifetime of measures (approx) (years)',blank=True, null=True)
    energyconsumptionbefore_31 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please state the energy consumption before intervention in MWh/a. Total billed annual energy use (all sources)',blank=True, null=True)
    energyperformancecertificatebefore_32 = models.CharField(max_length=500, help_text='What was the energy performance cerificate rating before intervention?',blank=True, null=True)
    breakdownofconsumptionbyfueltype_33 = models.CharField(max_length=500, help_text='Energy consumption before intervention breakdown by fuel',blank=True, null=True)
    breakdownofconsumptionbyenduse_34 = models.CharField(max_length=500, help_text='Energy consumption before intervention end use',blank=True, null=True)
    sourceofconsumptionbefore_35 = models.CharField(max_length=500, help_text='Please select what was the source of consumption before intervention from the list', choices = SOURCECONSUMPTIONBEFORE, blank=True, null=True)
    sourceofconsumptionbeforeother_35 = models.CharField(max_length=500, help_text='Please specify the source of consumption',blank=True, null=True)
    predictedenergyconsumptionafter_36 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify the Predicted Energy Consumption AFTER intervention in MWh/a',blank=True, null=True)
    whatisthebasisoftheforecast_37 = models.CharField(max_length=500, help_text='Please select what is the basis of the forecast',choices = BASISFORECAST, blank=True, null=True)
    whatisthebasisoftheforecastother_37 = models.CharField(max_length=500, help_text='Please specify other',blank=True, null=True)
    energyconsumptionafter_38 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify the Energy Consumption AFTER intervention (actual) in MWh/a.Total billed annual energy use (all sources)',blank=True, null=True)
    energyperformancecertificateafter_39 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Energy Performance Certificate rating AFTER intervention',blank=True, null=True)
    breakdownofconsumptionbyfueltype_40 = models.CharField(max_length=500, help_text='Energy consumption after intervention breakdown by fuel to be filled in indicator (141) - (151)',blank=True, null=True)
    sourceofconsumptionafter_41 = models.CharField(max_length=500, help_text='Please specify source of consumption after intervention (actual)',choices = SOURCECONSUMPTIONAFTER, blank=True, null=True)
    sourceofconsumptionafterother_41 = models.CharField(max_length=500, help_text='Please specify other',blank=True,null=True)
    havetheprojectenergysavingsbeenverified_42 = models.CharField(max_length=50, help_text='Please select if and how the project energy savings have been independently verified',blank=True, null=True, choices = VERIFIED)
    methodologyforindependentverification_43 = models.CharField(max_length=500, help_text='Please state the methodology for independent verification (e.g. IPMVP)',blank=True, null=True)
    productionrate_44 = models.DecimalField(max_digits=25, decimal_places=2, help_text='Please specify any adjustments that need to be made in order to make the BEFORE and ACTUAL AFTER energy use directly comparable.  For example, if production rate is increased by 10% in the AFTER period compared to BEFORE, insert +10% .  LEAVE BLANK IF NO SIGNIFICANT CHANGE',blank=True, null=True)
    floorarea_45 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify the floor area',blank=True, null=True)
    comfort_46 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify comfort',blank=True, null=True)
    heatingload_47 = models.DecimalField(max_digits=25,decimal_places=2, help_text='Please specify heating load',blank=True, null=True)
    coolingload_48 = models.DecimalField(max_digits=25,decimal_places=2, help_text='Please specify cooling load',blank=True, null=True)
    totalvalueofasset_49 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify Total Value  of Asset (in Euro)',blank=True, null=True)
    totalvalueofinvestment_50 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify Total Value  of investment (inclusive of EE component)',blank=True, null=True)
    valueofeeinvestment_51 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify Value of EE investment (in Euro)',blank=True, null=True)
    annualenergycostsavings_52 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify Annual energy cost savings (latest, or representative year) (in Euro)',blank=True, null=True)
    additionalfinancialbenefits_53 = models.DecimalField(max_digits=25, decimal_places=2,max_length=500, help_text='Please specify Additional financial benefits (e.g. maintenance savings) (in Euro)',blank=True, null=True)
    additionalcosts_54 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify Additional costs (in Euro)',blank=True, null=True)
    netannualsaving_55 = models.DecimalField(max_digits=25, decimal_places=2,max_length=500, help_text='Please specify Net annual saving',blank=True, null=True)
    npvprior_56 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify NPV (computed prior to investment)',blank=True, null=True)
    npvactual_57 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify NPV actual',blank=True, null=True)
    irrprior_58 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify IRR (computed prior to investment)',blank=True, null=True)
    irractual_59 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify IRR actual',blank=True, null=True)
    sourceoffinance_60 = models.CharField(max_length=500,help_text='Please specify Source of finance',blank=True, null=True)
    valueofgrant_61 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify Value of grant/subsidy (if any) (in Euro)',blank=True, null=True)
    provider_62 = models.CharField(max_length=500, help_text='Please specify Provider',blank=True, null=True)
    valueofloan_63 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify Value of loan (if any) (in Euro)',blank=True, null=True)
    loanrepaymentterm_64 = models.DecimalField(max_digits=25, decimal_places=0,help_text='Please specify Loan repayment term',blank=True, null=True)
    interestrate_65 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify Interest rate',blank=True, null=True)
    keyreasonsformakinginvestment_66 = models.CharField(max_length=500, help_text='Please state key reasons for making investment',blank=True, null=True)
    nonfinancialbenefits_67 = models.ManyToManyField(Benefit, help_text='Please state any non-financial benefits realised by the project',blank=True)
    financialperformance_68 = models.CharField(max_length=500, help_text='Please rate actual financial performance compared with expectation',blank=True, null=True, choices = SATISFACTION)
    overallsatisfaction_69 = models.CharField(max_length=500, help_text='Please rate overall satisfaction with the investment',blank=True, null=True,choices = SATISFACTION)
    otherinformation_70 = models.TextField( help_text='Please describe/attach any other information you would like to share concerning your investment, e.g. technical specifications, before/after status, etc',blank=True, null=True)
    energysavingstotal_71 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, total',blank=True, null=True)
    energysavingsgridelectricity_72 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, grid electricity',blank=True, null=True)
    energysavingsgas_73 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, gas',blank=True, null=True)
    energysavingsoil_74 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, oil',blank=True, null=True)
    energysavingscoal_75 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, coal/coal-based products',blank=True, null=True)
    energysavingsdistrictheating_76 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, district heating',blank=True, null=True)
    energysavingsdistrictcooling_77 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, district cooling',blank=True, null=True)
    energysavingsCHP_78 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, CHP',blank=True, null=True)
    energysavingsbiomass_79 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, biomass',blank=True, null=True)
    energysavingsbiofuels_80 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, biofuels',blank=True, null=True)
    energysavingselectricity_81 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, renewable electricity',blank=True, null=True)
    energysavingsrenewableheat_82 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings, renewable heat',blank=True, null=True)
    adjustedenergysavingstotal_83 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, total',blank=True, null=True)
    adjustedenergysavingstotalgridelectricity_84 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, grid electricity',blank=True, null=True)
    adjustedenergysavingstotalgas_85 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, gas',blank=True, null=True)
    adjustedenergysavingstotaloil_86 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, oil',blank=True, null=True)
    adjustedenergysavingstotalcoal_87 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, coal/coal-based products',blank=True, null=True)
    adjustedenergysavingstotaldistrictheating_88 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, district heating',blank=True, null=True)
    adjustedenergysavingstotaldistrictcooling_89 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, district cooling',blank=True, null=True)
    adjustedenergysavingstotalCHP_90 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, CHP',blank=True, null=True)
    adjustedenergysavingstotalbiomass_91 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, biomass',blank=True, null=True)
    adjustedenergysavingstotalbiofuels_92 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, biofuels',blank=True, null=True)
    adjustedenergysavingstotalrenewableelectricity_93 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, renewable electricity',blank=True, null=True)
    adjustedenergysavingstotalrenewableheat_94 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy savings adjusted for weather/season/production, renewable heat',blank=True, null=True)
    hastheadjustedenergysavingsverified_95 = models.CharField(max_length=500,help_text='Please specify Have the adjusted project energy savings been independently verified?',blank=True, null=True, choices = VERIFIED)
    energypricebeforetotal_96 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, total',blank=True, null=True)
    energypricebeforegridelectricity_97 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, grid electricity',blank=True, null=True)
    energypricebeforegas_98 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, gas',blank=True, null=True)
    energypricebeforeoil_99 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, oil',blank=True, null=True)
    energypricebeforecoal_100 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, coal/coal-based products',blank=True, null=True)
    energypricebeforedistrictheating_101 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, district heating',blank=True, null=True)
    energypricebeforedistrictcooling_102 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, district cooling',blank=True, null=True)
    energypricebeforeCHP_103 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, CHP',blank=True, null=True)
    energypricebeforebiomass_104 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, biomass',blank=True, null=True)
    energypricebeforebiofuels_105 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, biofuels',blank=True, null=True)
    energypricebeforerenewableelectricity_106 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, renewable electricity',blank=True, null=True)
    energypricebeforerenewableheat_107 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price before intervention, EUR/kWh, renewable heat',blank=True, null=True)
    energypriceaftertotal_108 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, total',blank=True, null=True)
    energypriceaftergridelectricity_109 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, grid electricity',blank=True, null=True)
    energypriceaftergas_110 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, gas',blank=True, null=True)
    energypriceafteroil_111 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, oil',blank=True, null=True)
    energypriceaftercoal_112 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, coal/coal-based products',blank=True, null=True)
    energypriceafterdistrictheating_113 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, district heating',blank=True, null=True)
    energypriceafterdistrictcooling_114 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, district cooling',blank=True, null=True)
    energypriceafterCHP_115 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, CHP',blank=True, null=True)
    energypriceafterbiomass_116 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, biomass',blank=True, null=True)
    energypriceafterbiofuels_117 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, biofuels',blank=True, null=True)
    energypriceafterrenewableelectricity_118 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, renewable electricity',blank=True, null=True)
    energypriceafterrenewableheat_119 = models.DecimalField(max_digits=25, decimal_places=2,help_text='Please specify energy price after intervention, EUR/kWh, renewable heat',blank=True, null=True)
    energyconsbeforegridelectricity_120 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, grid electricity',blank=True, null=True)
    energyconsbeforegas_121 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, gas',blank=True, null=True)
    energyconsbeforeoil_122 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, oil',blank=True, null=True)
    energyconsbeforecoal_123 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, coal/coal-based products',blank=True, null=True)
    energyconsbeforedistrictheating_124 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, district heating',blank=True, null=True)
    energyconsbeforedistrictcooling_125 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, district cooling',blank=True, null=True)
    energyconsbeforeCHP_126 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, CHP',blank=True, null=True)
    energyconsbeforebiomass_127 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, biomass',blank=True, null=True)
    energyconsbeforebiofuels_128 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, biofuels',blank=True, null=True)
    energyconsbeforerenewableelectricity_129 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, renewable electricity',blank=True, null=True)
    energyconsbeforerenewableheat_130 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, renewable heat',blank=True, null=True)
    energyconsbeforespaceheating_131 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, space heating',blank=True, null=True)
    energyconsbeforespacecooling_132 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, space cooling',blank=True, null=True)
    energyconsbeforewaterheating_133 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, water heating',blank=True, null=True)
    energyconsbeforeventilation_134 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, ventilation',blank=True, null=True)
    energyconsbeforerefrigeration_135 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, refrigeration',blank=True, null=True)
    energyconsbeforepumps_136 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, pumps and fans',blank=True, null=True)
    energyconsbeforecatering_137 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, catering',blank=True, null=True)
    energyconsbeforeprocessenergy_138 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, process energy',blank=True, null=True)
    energyconsbeforelighting_139 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, lighting',blank=True, null=True)
    energyconsbeforeappliances_140 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, appliances',blank=True, null=True)
    energyconsaftergridelectricity_141 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, grid electricity',blank=True, null=True)
    energyconsaftergas_142 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, gas',blank=True, null=True)
    energyconsafteroil_143 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, oil',blank=True, null=True)
    energyconsaftercoal_144 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, coal/coal-based products',blank=True, null=True)
    energyconsafterdistrictheating_145 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, district heating',blank=True, null=True)
    energyconsafterdistrictcooling_146 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, district cooling',blank=True, null=True)
    energyconsafterCHP_147 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, CHP',blank=True, null=True)
    energyconsafterbiomass_148 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, biomass',blank=True, null=True)
    energyconsafterbiofuels_149 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, biofuels',blank=True, null=True)
    energyconsafterrenewableelectricity_150 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, renewable electricity',blank=True, null=True)
    energyconsafterrenewableheat_151 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, renewable heat',blank=True, null=True)
    energyconsafterspaceheating_152 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, space heating',blank=True, null=True)
    energyconsafterspacecooling_153 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, space cooling',blank=True, null=True)
    energyconsafterwaterheating_154 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, water heating',blank=True, null=True)
    energyconsafterventilation_155 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, ventilation',blank=True, null=True)
    energyconsafterrefrigeration_156 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, refrigeration',blank=True, null=True)
    energyconsafterpumps_157 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, pumps and fans',blank=True, null=True)
    energyconsaftercatering_158 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, catering',blank=True, null=True)
    energyconsafterprocessenergy_159 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, process energy',blank=True, null=True)
    energyconsafterlighting_160 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, lighting',blank=True, null=True)
    energyconsafterppliances_161 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, appliances',blank=True, null=True)
    adjustedenergyconsbeforetotal_162 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, total',blank=True, null=True)
    adjustedenergyconsbeforegridelectricity_163 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, grid electricity',blank=True, null=True)
    adjustedenergyconsbeforegas_164 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, gas',blank=True, null=True)
    adjustedenergyconsbeforeoil_165 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, oil',blank=True, null=True)
    adjustedenergyconsbeforecoal_166 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, coal/coal-based products',blank=True, null=True)
    adjustedenergyconsbeforedistrictheating_167 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, district heating',blank=True, null=True)
    adjustedenergyconsbeforedistrictcooling_168 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, district cooling',blank=True, null=True)
    adjustedenergyconsbeforeCHP_169 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, CHP',blank=True, null=True)
    adjustedenergyconsbeforebiomass_170 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, biomass',blank=True, null=True)
    adjustedenergyconsbeforebiofuels_171 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, biofuels',blank=True, null=True)
    adjustedenergyconsbeforerenewableelectricity_172 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, renewable electricity',blank=True, null=True)
    adjustedenergyconsbeforerenewableheat_173 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, renewable heat',blank=True, null=True)
    adjustedenergyconsbeforespaceheating_174 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, space heating',blank=True, null=True)
    adjustedenergyconsbeforespacecooling_175 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, space cooling',blank=True, null=True)
    adjustedenergyconsbeforewaterheating_176 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, water heating',blank=True, null=True)
    adjustedenergyconsbeforeventilation_177 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, ventilation',blank=True, null=True)
    adjustedenergyconsbeforerefrigeration_178 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, refrigeration',blank=True, null=True)
    adjustedenergyconsbeforepumps_179 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, pumps and fans',blank=True, null=True)
    adjustedenergyconsbeforecatering_180 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, catering',blank=True, null=True)
    adjustedenergyconsbeforeprocessenergy_181 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, process energy',blank=True, null=True)
    adjustedenergyconsbeforelighting_182 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, lighting',blank=True, null=True)
    adjustedenergyconsbeforeappliances_183 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption before intervention, adjusted for weather/season/production, appliances',blank=True, null=True)
    adjustedenergyconsaftertotal_184 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, total',blank=True, null=True)
    adjustedenergyconsaftergridelectricity_185 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, grid electricity',blank=True, null=True)
    adjustedenergyconsaftergas_186 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, gas',blank=True, null=True)
    adjustedenergyconsafteroil_187 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, oil',blank=True, null=True)
    adjustedenergyconsaftercoal_188 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, coal/coal-based products',blank=True, null=True)
    adjustedenergyconsafterdistrictheating_189 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, district heating',blank=True, null=True)
    adjustedenergyconsafterdistrictcooling_190 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, district cooling',blank=True, null=True)
    adjustedenergyconsafterCHP_191 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, CHP',blank=True, null=True)
    adjustedenergyconsafterbiomass_192 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, biomass',blank=True, null=True)
    adjustedenergyconsafterbiofuels_193 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, biofuels',blank=True, null=True)
    adjustedenergyconsafterrenewableelectricity_194 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, renewable electricity',blank=True, null=True)
    adjustedenergyconsafterrenewableheat_195 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, renewable heat',blank=True, null=True)
    adjustedenergyconsafterspaceheating_196 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, space heating',blank=True, null=True)
    adjustedenergyconsafterspacecooling_197 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, space cooling',blank=True, null=True)
    adjustedenergyconsafterwaterheating_198 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, water heating',blank=True, null=True)
    adjustedenergyconsafterventilation_199 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, ventilation',blank=True, null=True)
    adjustedenergyconsafterrefrigeration_200 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, refrigeration',blank=True, null=True)
    adjustedenergyconsafterpumps_201 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, pumps and fans',blank=True, null=True)
    adjustedenergyconsaftercatering_202 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, catering',blank=True, null=True)
    adjustedenergyconsafterprocessenergy_203 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, process energy',blank=True, null=True)
    adjustedenergyconsafterlighting_204 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, lighting',blank=True, null=True)
    adjustedenergyconsafterappliances_205 = models.DecimalField(max_digits=25, decimal_places=4,help_text='Please specify energy consumption after intervention, adjusted for weather/season/production, appliances',blank=True, null=True)